import { BotOff, Inbox, MessageSquareText } from "lucide-react";
import { CHANNEL_TYPES } from "@/modules/channels/core/channel-contracts";
import { ConversationComposer } from "@/modules/channels/components/conversation-composer";
import { ConversationControls } from "@/modules/channels/components/conversation-controls";
import type { QuickReplyTemplate } from "@/modules/channels/types/quick-reply";
import type { OmnichannelInboxData } from "../types/omnichannel-inbox";

export function OmnichannelInboxView({accounts,conversations,profiles,tags,selectedChannelType,selectedAccountId,error,quickReplies}:OmnichannelInboxData&{quickReplies:QuickReplyTemplate[]}){
  return <div className="space-y-5">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Omnichannel workspace</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Unified Inbox</h1><p className="mt-1 text-sm text-slate-500">One queue for email, Facebook, Zalo and future channels.</p></div><form className="flex flex-wrap gap-2"><select name="channel" defaultValue={selectedChannelType??""} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All channels</option>{CHANNEL_TYPES.map(type=><option key={type}>{type}</option>)}</select><select name="account" defaultValue={selectedAccountId??""} className="h-10 rounded-lg border bg-white px-3 text-sm"><option value="">All accounts</option>{accounts.map(account=><option key={account.id} value={account.id}>{account.channelType} · {account.displayName}</option>)}</select><button className="h-10 rounded-lg border bg-white px-4 text-sm font-semibold">Apply</button></form></header>
    {error?<div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-sm text-amber-900">{error}</div>:conversations.length===0?<div className="rounded-xl border border-dashed bg-white p-14 text-center"><Inbox className="mx-auto text-slate-400"/><h2 className="mt-4 font-semibold">No omnichannel conversations yet</h2></div>:<section className="overflow-hidden rounded-xl border bg-white"><div className="border-b px-5 py-4 text-sm font-semibold">Latest 50 conversations</div><div className="divide-y">{conversations.map(conversation=><article key={conversation.id} className="flex gap-4 p-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-slate-100"><MessageSquareText size={18}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-blue-50 px-2 py-0.5 text-xs font-semibold text-blue-700">{conversation.channelType}</span><h2 className="truncate text-sm font-semibold">{conversation.subject??conversation.senderExternalId??"Conversation"}</h2>{conversation.takeoverMode==="HUMAN_TAKEOVER"?<span className="inline-flex items-center gap-1 text-xs text-amber-700"><BotOff size={12}/>Human takeover</span>:null}</div><p className="mt-1 truncate text-sm text-slate-500">{conversation.latestText??"Attachment or provider event"}</p><ConversationControls conversationId={conversation.id} status={conversation.status} takeoverMode={conversation.takeoverMode} assignedTo={conversation.assignedTo} profiles={profiles} tags={tags} tagIds={conversation.tagIds}/><ConversationComposer conversationId={conversation.id} channelType={conversation.channelType} proposedActions={conversation.proposedActions} quickReplies={quickReplies}/></div><div className="text-right"><p className="text-xs font-semibold text-slate-600">{conversation.status}</p>{conversation.unreadCount>0?<span className="mt-1 inline-block rounded-full bg-blue-600 px-2 py-0.5 text-xs text-white">{conversation.unreadCount}</span>:null}</div></article>)}</div></section>}
  </div>;
}
