-- READ ONLY. Run before migration 016. It intentionally returns booleans.
with columns as(select table_name,column_name from information_schema.columns where table_schema='public'),
constraints as(select conrelid,confrelid,contype,pg_get_constraintdef(oid) definition from pg_constraint),
indexes as(select tablename,indexname,indexdef from pg_indexes where schemaname='public')
select
 to_regclass('public.email_campaigns') is not null as campaigns_exist,
 to_regclass('public.email_campaign_senders') is not null as campaign_senders_exist,
 to_regclass('public.email_campaign_recipients') is not null as campaign_recipients_exist,
 to_regclass('public.email_campaign_events') is not null as campaign_events_exist,
 to_regclass('public.email_suppressions') is not null as suppressions_exist,
 to_regclass('public.email_sender_limits') is not null as sender_limits_exist,
 to_regclass('public.email_sender_usage') is not null as sender_usage_exist,
 to_regclass('public.email_campaign_sender_usage') is not null as campaign_sender_usage_exist,
 to_regclass('public.email_send_requests') is not null as send_requests_exist,
 to_regclass('public.email_messages') is not null as messages_exist,
 to_regclass('public.email_threads') is not null as threads_exist,
 (select count(*)=7 from columns where table_name='email_send_requests' and column_name in('id','workspace_id','email_account_id','send_type','status','idempotency_key','to_addresses')) as send_request_columns_compatible,
 exists(select 1 from constraints where conrelid='public.email_send_requests'::regclass and contype='u' and regexp_replace(definition,'[[:space:]]','','g')='UNIQUE(id,workspace_id)') as send_request_composite_unique,
 exists(select 1 from constraints where conrelid='public.email_accounts'::regclass and contype='u' and definition ilike '%id%workspace_id%') as account_composite_unique,
 exists(select 1 from constraints where conrelid='public.email_campaign_recipients'::regclass and contype='u' and definition ilike '%id%workspace_id%') as recipient_composite_unique,
 exists(select 1 from indexes where tablename='email_sender_usage' and indexdef ilike '%workspace_id%email_account_id%bucket_kind%bucket_start%') as global_usage_unique_index,
 to_regprocedure('public.claim_email_campaign_recipients(uuid,uuid,uuid,integer)') is not null as legacy_claim_exists,
 to_regprocedure('public.finalize_email_campaign_recipient(uuid,uuid,uuid,text,uuid,text)') is not null as legacy_finalizer_exists,
 to_regclass('public.email_campaign_steps') is null as steps_absent,
 to_regclass('public.email_campaign_recipient_steps') is null as recipient_steps_absent,
 to_regclass('public.email_campaign_signal_events') is null as signal_events_absent,
 not exists(select 1 from columns where table_name='email_campaigns' and column_name='sequence_enabled') as sequence_flag_absent,
 not exists(select 1 from columns where table_name='email_messages' and column_name in('dsn_status','dsn_action','dsn_final_recipient')) as dsn_columns_absent,
 to_regprocedure('public.initialize_email_campaign_sequence(uuid,uuid)') is null as initialize_rpc_absent,
 to_regprocedure('public.claim_email_campaign_sequence_steps(uuid,uuid,uuid,integer)') is null as sequence_claim_absent,
 to_regprocedure('public.finalize_email_campaign_sequence_step(uuid,uuid,uuid,text,uuid,text)') is null as sequence_finalizer_absent,
 to_regprocedure('public.apply_email_campaign_signal(uuid,uuid,text,text,uuid,text)') is null as signal_rpc_absent;
