import {test,expect} from "@playwright/test";
import path from "node:path";

const email="phase51-local@hirex.test",password="HireX-Local-Only-51!";
test.beforeEach(async({page})=>{await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:/sign in/i}).click();await expect(page).toHaveURL(/\/(?:campaigns)?$/);});
test("captured authentication survives a fresh browser context",async({page,browser})=>{const state=path.resolve("runtime/phase51-local/authenticated-state.json");await page.context().storageState({path:state});const fresh=await browser.newContext({storageState:state});const freshPage=await fresh.newPage();await freshPage.goto("/campaigns");await expect(freshPage).toHaveURL(/\/campaigns$/);await expect(freshPage.getByText("PHASE-5-LOCAL-E2E")).toBeVisible();await fresh.close();});
test("authenticated campaign detail attachments and secure download",async({page})=>{await page.goto("/campaigns");await expect(page.getByText("PHASE-5-LOCAL-E2E")).toBeVisible();await page.getByText("PHASE-5-LOCAL-E2E").click();await expect(page.getByText("Hồ sơ ứng viên.txt")).toBeVisible();await expect(page.getByText("pricing.csv")).toBeVisible();const download=page.waitForEvent("download");await page.getByText("Hồ sơ ứng viên.txt").click();const item=await download;expect(await item.createReadStream()).toBeTruthy();});
test("cross-workspace user cannot download a campaign attachment",async({browser})=>{const context=await browser.newContext();const page=await context.newPage();await page.goto("/login");await page.getByLabel("Email").fill("phase51-cross@hirex.test");await page.getByLabel("Password").fill("HireX-Cross-Only-51!");await page.getByRole("button",{name:/sign in/i}).click();await expect(page).toHaveURL(/\/campaigns$/);const response=await page.goto("/api/campaigns/95000000-0000-4000-8000-000000000003/attachments/95000000-0000-4000-8000-000000000006");expect(response?.status()).toBe(404);await context.close();});
test("wizard uploads, persists, reorders and removes a UTF-8 attachment",async({page})=>{const url="/campaigns/new?campaignId=95000000-0000-4000-8000-000000000003&stage=sequence";await page.goto(url);const initial=page.locator("div.rounded-xl.border.p-5").first();await initial.locator('input[type="file"]').setInputFiles({name:"Báo giá thử nghiệm.txt",mimeType:"text/plain",buffer:Buffer.from("phase51 local attachment")});await initial.getByRole("button",{name:"Upload"}).click();await expect(initial.getByText(/Báo giá thử nghiệm\.txt/)).toBeVisible();await page.reload();await expect(initial.getByText(/Báo giá thử nghiệm\.txt/)).toBeVisible();const pricing=initial.getByText(/pricing\.csv/).locator("..");await pricing.getByRole("button",{name:"Up"}).click();await page.reload();const attachmentRows=initial.locator("div.mt-3.space-y-2 > div");await expect(attachmentRows.first()).toContainText("pricing.csv");await initial.getByRole("button",{name:"Remove Báo giá thử nghiệm.txt"}).click();await expect(initial.getByText(/Báo giá thử nghiệm\.txt/)).toHaveCount(0);});
test("wizard, suppressions and worker health render",async({page})=>{await page.goto("/campaigns/new?campaignId=95000000-0000-4000-8000-000000000003&stage=sequence");await expect(page.getByText("Hồ sơ ứng viên.txt")).toBeVisible();await page.goto("/campaigns/new?campaignId=95000000-0000-4000-8000-000000000003&stage=review");await expect(page.getByText(/2 attachments/)).toBeVisible();await page.goto("/settings/suppressions");await expect(page.getByText("suppressed@hirex.test")).toBeVisible();await page.goto("/settings/email-automation");await expect(page.getByText("Healthy",{exact:true})).toBeVisible();for(const label of ["Scheduler installation","Worker health","Last run","Last successful run","Last duration","Runs today","Messages sent","Failures / delivery unknown"]){await expect(page.getByText(label,{exact:true})).toBeVisible();}});
for(const viewport of [{width:1366,height:768},{width:1440,height:900},{width:1920,height:1080}])test(`responsive ${viewport.width}x${viewport.height}`,async({page})=>{await page.setViewportSize(viewport);for(const path of ["/campaigns","/campaigns/95000000-0000-4000-8000-000000000003","/campaigns/new?campaignId=95000000-0000-4000-8000-000000000003&stage=sequence","/settings/suppressions"]){await page.goto(path);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1)).toBeTruthy();}});
