"use client";
import { useActionState } from "react";
import { reviewAutomationProposal, saveChannelAutomation } from "../server/channel-actions";
import type { ChannelAutomationProposalSummary, ChannelAutomationSummary } from "../types/automation";
import type { ChannelActionState } from "../types/channel-action-state";
const initial:ChannelActionState={status:"idle",message:null};

export function AutomationManager({automations,proposals,error}:{automations:ChannelAutomationSummary[];proposals:ChannelAutomationProposalSummary[];error:string|null}){
  const[state,action,pending]=useActionState(saveChannelAutomation,initial);
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Omnichannel</p><h1 className="text-3xl font-bold">Workflow automation</h1><p className="mt-1 text-sm text-slate-500">Inbound triggers create reviewable internal actions. Provider delivery is never executed directly.</p></header>{error?<div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">{error}</div>:null}<section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Create workflow</h2><form action={action} className="mt-4 grid gap-3 md:grid-cols-2"><input name="name" required maxLength={120} placeholder="Workflow name" className="rounded-lg border px-3 py-2 text-sm"/><select name="enabled" defaultValue="false" className="rounded-lg border px-3 py-2 text-sm"><option value="false">Disabled draft</option><option value="true">Enabled</option></select><select name="triggerType" defaultValue="KEYWORD_MATCHED" className="rounded-lg border px-3 py-2 text-sm"><option>MESSAGE_RECEIVED</option><option>KEYWORD_MATCHED</option><option>TAG_ADDED</option><option>CONVERSATION_ASSIGNED</option><option>SCHEDULED</option></select><input name="keywords" placeholder="Keywords separated by comma or semicolon" className="rounded-lg border px-3 py-2 text-sm"/><select name="actionType" defaultValue="PROPOSE_MESSAGE" className="rounded-lg border px-3 py-2 text-sm"><option>PROPOSE_MESSAGE</option><option>ADD_TAG</option><option>REMOVE_TAG</option><option>ASSIGN_CONVERSATION</option><option>SET_CONVERSATION_STATUS</option><option>CREATE_TASK</option></select><textarea name="actionConfiguration" defaultValue='{"text":"Thanks for contacting us."}' className="min-h-24 rounded-lg border px-3 py-2 font-mono text-sm"/><button disabled={pending} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending?"Saving…":"Save workflow"}</button>{state.message?<p className="self-center text-sm">{state.message}</p>:null}</form></section><section className="rounded-xl border bg-white"><div className="border-b px-5 py-4 font-semibold">Pending human review</div>{proposals.map(item=><Proposal key={item.id} value={item}/>)}{proposals.length===0?<p className="p-6 text-sm text-slate-500">No pending automation proposals.</p>:null}</section><section className="rounded-xl border bg-white"><div className="border-b px-5 py-4 font-semibold">Workflows</div><div className="divide-y">{automations.map(item=><article key={item.id} className="flex items-center justify-between p-4"><div><p className="font-semibold">{item.name}</p><p className="text-xs text-slate-500">{item.triggerType} · version {item.version}</p></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${item.enabled?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{item.enabled?"Enabled":"Draft"}</span></article>)}</div></section></div>
}
function Proposal({value}:{value:ChannelAutomationProposalSummary}){const[state,action,pending]=useActionState(reviewAutomationProposal,initial);return <article className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><p className="font-semibold">{value.actionType}</p><p className="text-xs text-slate-500">{value.automationName} · {new Date(value.createdAt).toLocaleString()}</p></div><div className="flex gap-2"><form action={action}><input type="hidden" name="proposalId" value={value.id}/><input type="hidden" name="approved" value="false"/><button disabled={pending} className="rounded border px-3 py-1 text-xs">Reject</button></form><form action={action}><input type="hidden" name="proposalId" value={value.id}/><input type="hidden" name="approved" value="true"/><button disabled={pending} className="rounded bg-emerald-600 px-3 py-1 text-xs font-semibold text-white">Approve</button></form></div>{state.message?<p className="w-full text-xs">{state.message}</p>:null}</article>}
