"use client";
import { useActionState } from "react";
import { MessageSquareMore, ShieldCheck } from "lucide-react";
import type { ChannelAccountsResult } from "../types/channel-account";
import { disconnectChannelAccount, setChannelAccountOperatorEnabled } from "../server/connect-channel-actions";
import type { ChannelActionState } from "../types/channel-action-state";
const initial:ChannelActionState={status:"idle",message:null};
export function ChannelAccountsView({result}:{result:ChannelAccountsResult}){return <div className="space-y-6"><div><p className="text-sm font-semibold text-blue-600">OMNICHANNEL</p><h1 className="text-2xl font-semibold text-slate-950">Channel accounts</h1><p className="mt-1 text-sm text-slate-500">Manage Facebook Pages, Zalo bridges and future messaging accounts.</p></div>{result.error?<div className="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">{result.error} Apply and review the required channel migrations before connecting providers.</div>:null}{!result.error&&result.accounts.length===0?<div className="rounded-xl border border-dashed bg-white p-10 text-center"><MessageSquareMore className="mx-auto text-slate-400"/><h2 className="mt-3 font-semibold">No channel accounts yet</h2></div>:null}<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{result.accounts.map(account=><article key={account.id} className="rounded-xl border bg-white p-5"><div className="flex items-center justify-between"><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold">{account.channelType}</span><span className="text-xs text-slate-500">{account.status}</span></div><h2 className="mt-4 font-semibold">{account.displayName??account.externalAccountId}</h2><p className="text-sm text-slate-500">{account.provider}</p>{account.channelType==="ZALO"?<div className="mt-3 space-y-1 text-xs text-slate-600"><p>Configuration: Configured</p><p>Operator state: {account.operatorEnabled?"Enabled":"Disabled"}</p><p>Provider health: {account.providerHealthStatus.replaceAll("_"," ")}</p><p>Last health check: {account.providerHealthCheckedAt?new Date(account.providerHealthCheckedAt).toLocaleString():"Never"}</p><OperatorToggle id={account.id} enabled={account.operatorEnabled}/></div>:null}<div className="mt-4 flex items-center justify-between gap-2 text-xs text-slate-500"><span className="inline-flex items-center gap-2"><ShieldCheck size={14}/>Credentials remain server-only</span>{account.channelType!=="EMAIL"&&account.status!=="DISCONNECTED"?<Disconnect id={account.id}/>:null}</div></article>)}</div></div>}
function Disconnect({id}:{id:string}){const[state,action,pending]=useActionState(disconnectChannelAccount,initial);return <form action={action}><input type="hidden" name="id" value={id}/><button disabled={pending} className="font-semibold text-rose-600">Disconnect</button>{state.message?<span className="sr-only">{state.message}</span>:null}</form>}
function OperatorToggle({id,enabled}:{id:string;enabled:boolean}){const[state,action,pending]=useActionState(setChannelAccountOperatorEnabled,initial);return <form action={action}><input type="hidden" name="id" value={id}/><input type="hidden" name="enabled" value={enabled?"false":"true"}/><button disabled={pending} className="font-semibold text-blue-700">{enabled?"Disable":"Enable"}</button>{state.message?<span className="sr-only">{state.message}</span>:null}</form>}
