"use client";
import { useActionState } from "react";
import { createManualChannelSuppression, deleteManualChannelSuppression } from "../server/channel-actions";
import type { ChannelActionState } from "../types/channel-action-state";
import type { ChannelSuppressionSummary } from "../types/channel-suppression";

const initial: ChannelActionState = { status: "idle", message: null };
export function ChannelSuppressionsManager({ suppressions, error }: { suppressions: ChannelSuppressionSummary[]; error: string | null }) {
  const [createState, createAction, creating] = useActionState(createManualChannelSuppression, initial);
  const [deleteState, deleteAction, deleting] = useActionState(deleteManualChannelSuppression, initial);
  return <div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Safety</p><h1 className="text-3xl font-bold">Channel suppressions</h1><p className="mt-1 text-sm text-slate-500">Stop outreach to a recipient across a specific channel. Strong provider and consent signals cannot be removed here.</p></header>{error ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error}</div> : null}<form action={createAction} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-[180px_1fr_auto]"><select name="channelType" className="rounded-lg border px-3 py-2 text-sm">{["EMAIL","FACEBOOK","ZALO","WHATSAPP","VIBER","TELEGRAM","OTHER"].map((value) => <option key={value}>{value}</option>)}</select><input name="recipient" required maxLength={512} placeholder="Email, phone or provider recipient ID" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={creating} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Suppress</button>{createState.message ? <p className="text-sm md:col-span-3">{createState.message}</p> : null}</form><section className="overflow-hidden rounded-xl border bg-white"><div className="grid grid-cols-[120px_1fr_140px_140px_auto] gap-3 border-b bg-slate-50 px-4 py-3 text-xs font-semibold uppercase text-slate-500"><span>Channel</span><span>Recipient</span><span>Reason</span><span>Source</span><span/></div>{suppressions.map((item) => <div key={item.id} className="grid grid-cols-[120px_1fr_140px_140px_auto] items-center gap-3 border-b px-4 py-3 text-sm"><span>{item.channelType}</span><span className="truncate">{item.recipient}</span><span>{item.reason}</span><span>{item.source}</span>{item.reason === "MANUAL" && item.source === "OPERATOR" ? <form action={deleteAction}><input type="hidden" name="id" value={item.id}/><button disabled={deleting} className="text-rose-600">Remove</button></form> : <span className="text-xs text-slate-400">Protected</span>}</div>)}{suppressions.length === 0 ? <p className="p-8 text-center text-sm text-slate-500">No channel suppressions.</p> : null}</section>{deleteState.message ? <p className="text-sm">{deleteState.message}</p> : null}</div>;
}
