"use client";
import { useActionState, useState } from "react";
import { connectFacebookPage, connectZaloBridge } from "../server/connect-channel-actions";
import type { ChannelActionState } from "../types/channel-action-state";
const initial:ChannelActionState={status:"idle",message:null};

export function ChannelConnectForms(){const[open,setOpen]=useState<"FACEBOOK"|"ZALO"|null>(null);return <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Connect a provider account</h2><p className="text-sm text-slate-500">Credentials are encrypted on the server and never returned to the browser.</p></div><div className="flex gap-2"><button onClick={()=>setOpen(open==="FACEBOOK"?null:"FACEBOOK")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Facebook Page</button><button onClick={()=>setOpen(open==="ZALO"?null:"ZALO")} className="rounded-lg border px-3 py-2 text-sm font-semibold">Zalo bridge</button></div></div>{open==="FACEBOOK"?<FacebookForm/>:null}{open==="ZALO"?<ZaloForm/>:null}</section>}
function FacebookForm(){const[state,action,pending]=useActionState(connectFacebookPage,initial);return <form action={action} className="mt-5 grid gap-3 md:grid-cols-2"><input name="pageId" required placeholder="Facebook Page ID" className="rounded-lg border px-3 py-2 text-sm"/><input name="displayName" placeholder="Display name" className="rounded-lg border px-3 py-2 text-sm"/><input name="graphApiVersion" required placeholder="Graph API version, e.g. vXX.X" className="rounded-lg border px-3 py-2 text-sm"/><input name="pageAccessToken" type="password" required autoComplete="off" placeholder="Page access token" className="rounded-lg border px-3 py-2 text-sm"/><input name="appSecret" type="password" required autoComplete="off" placeholder="Meta app secret" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={pending} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Save encrypted credential</button>{state.message?<p className="text-sm md:col-span-2">{state.message}</p>:null}</form>}
function ZaloForm(){const[state,action,pending]=useActionState(connectZaloBridge,initial);return <form action={action} className="mt-5 grid gap-3 md:grid-cols-2"><input name="accountId" required placeholder="Bridge account ID" className="rounded-lg border px-3 py-2 text-sm"/><input name="displayName" placeholder="Display name" className="rounded-lg border px-3 py-2 text-sm"/><input name="bridgeBaseUrl" type="url" required placeholder="https://bridge.example.com" className="rounded-lg border px-3 py-2 text-sm"/><input name="bridgeSecret" type="password" required autoComplete="off" placeholder="Signing secret" className="rounded-lg border px-3 py-2 text-sm"/><button disabled={pending} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Save encrypted bridge</button>{state.message?<p className="text-sm md:col-span-2">{state.message}</p>:null}</form>}
