"use client";
import { useActionState } from "react";
import { approveChannelMessage, proposeChannelMessage } from "../server/channel-actions";
import type { ChannelActionState } from "../types/channel-action-state";
import { generateOmnichannelDraft, type OmnichannelAiState } from "../server/omnichannel-ai-actions";
const initial:ChannelActionState={status:"idle",message:null};
const initialAi:OmnichannelAiState={status:"idle",message:null,draftText:null};
export function ConversationComposer({conversationId,proposedActions}:{conversationId:string;proposedActions:Array<{id:string;text:string|null;proposedBy:string}>}){const[state,propose,pending]=useActionState(proposeChannelMessage,initial);return <div className="mt-3 rounded-lg border bg-slate-50 p-3"><form action={propose} className="flex gap-2"><input type="hidden" name="conversationId" value={conversationId}/><textarea name="text" required placeholder="Write a reply or use a quick reply…" className="min-h-16 flex-1 rounded border bg-white px-3 py-2 text-sm"/><button disabled={pending} className="self-end rounded bg-blue-600 px-3 py-2 text-xs font-semibold text-white">Propose</button></form>{state.message?<p className="mt-2 text-xs text-slate-600">{state.message}</p>:null}<AiDraft conversationId={conversationId}/>{proposedActions.map(action=><Proposed key={action.id} action={action}/>)}</div>}
function Proposed({action}:{action:{id:string;text:string|null;proposedBy:string}}){const[state,approve,pending]=useActionState(approveChannelMessage,initial);return <div className="mt-2 flex items-center justify-between gap-2 rounded border bg-white p-2 text-xs"><span className="truncate">{action.proposedBy}: {action.text}</span><form action={approve}><input type="hidden" name="actionId" value={action.id}/><button disabled={pending} className="rounded bg-emerald-600 px-2 py-1 font-semibold text-white">Approve</button></form>{state.message?<span>{state.message}</span>:null}</div>}
function AiDraft({conversationId}:{conversationId:string}){const[state,action,pending]=useActionState(generateOmnichannelDraft,initialAi);const[proposalState,proposeAction,proposalPending]=useActionState(proposeChannelMessage,initial);return <div className="mt-2"><form action={action} className="flex gap-2"><input type="hidden" name="conversationId" value={conversationId}/><input name="instruction" maxLength={1000} placeholder="Optional AI drafting instruction" className="flex-1 rounded border bg-white px-2 py-1 text-xs"/><button disabled={pending} className="rounded border bg-white px-2 py-1 text-xs font-semibold">{pending?"Drafting…":"AI draft"}</button></form>{state.draftText?<form action={proposeAction} className="mt-2 flex gap-2"><input type="hidden" name="conversationId" value={conversationId}/><input type="hidden" name="proposedBy" value="AI_ASSIST"/><textarea name="text" readOnly value={state.draftText} className="min-h-16 flex-1 rounded border bg-white px-2 py-1 text-xs"/><button disabled={proposalPending} className="self-end rounded bg-blue-600 px-2 py-1 text-xs font-semibold text-white">Propose reviewed draft</button></form>:null}{proposalState.message?<p className="mt-1 text-xs text-slate-500">{proposalState.message}</p>:null}{state.message?<p className="mt-1 text-xs text-slate-500">{state.message}</p>:null}</div>}
