import Link from "next/link";
import { Plus,Search } from "lucide-react";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { listCampaigns } from "@/modules/campaigns/server/campaign-data";

const statuses=["DRAFT","SCHEDULED","RUNNING","PAUSED","COMPLETED","CANCELLED"];
const badge:Record<string,string>={DRAFT:"bg-slate-100 text-slate-700",SCHEDULED:"bg-violet-100 text-violet-700",RUNNING:"bg-emerald-100 text-emerald-700",PAUSED:"bg-amber-100 text-amber-700",COMPLETED:"bg-blue-100 text-blue-700",CANCELLED:"bg-rose-100 text-rose-700"};
export default async function CampaignsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}){const {q="",status=""}=await searchParams;const {campaigns,error}=await listCampaigns();const normalized=q.trim().toLowerCase();const visible=campaigns.filter(c=>(!normalized||c.name.toLowerCase().includes(normalized))&&(!statuses.includes(status)||c.status===status));const totals={active:campaigns.filter(c=>c.status==="RUNNING").length,scheduled:campaigns.filter(c=>c.status==="SCHEDULED").length,sent:campaigns.reduce((n,c)=>n+c.sent,0),replies:campaigns.reduce((n,c)=>n+c.replies,0),bounces:campaigns.reduce((n,c)=>n+c.hardBounces,0)};const contacted=campaigns.reduce((n,c)=>n+Math.min(c.sent,c.recipients),0);
return <><PageHeader title="Email Campaigns" description="Build, sequence and monitor safe Gmail outreach." action={<Button asChild><Link href="/campaigns/new"><Plus className="size-4"/>New Campaign</Link></Button>}/><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Active",totals.active],["Scheduled",totals.scheduled],["Emails sent",totals.sent],["Replies",totals.replies],["Reply rate",contacted?`${Math.round(totals.replies/contacted*100)}%`:"0%"],["Hard bounces",totals.bounces]].map(([label,value])=><div className="rounded-xl border bg-white p-4" key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><form className="mb-5 flex flex-col gap-2 rounded-xl border bg-white p-3 sm:flex-row"><label className="flex h-10 flex-1 items-center gap-2 rounded-lg border px-3"><Search className="size-4 text-slate-400"/><input name="q" defaultValue={q} placeholder="Search campaigns" className="w-full outline-none"/></label><select name="status" defaultValue={status} className="h-10 rounded-lg border px-3"><option value="">All statuses</option>{statuses.map(x=><option key={x}>{x}</option>)}</select><button className="rounded-lg border px-5 text-sm font-medium">Apply</button></form>{error?<div className="rounded-xl border bg-white p-8 text-sm text-rose-600">{error}</div>:visible.length===0?<div className="rounded-xl border border-dashed bg-white p-16 text-center"><h2 className="text-xl font-semibold">{campaigns.length?"No campaigns match":"No campaigns yet"}</h2><p className="mt-2 text-sm text-slate-500">{campaigns.length?"Adjust search or status filters.":"Create a draft, review audience and sequence, then launch."}</p></div>:<div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[1180px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr>{["Campaign","Status","Audience","Sent","Follow-ups","Replies","Reply rate","Bounce","Sender(s)","Next activity","Updated"].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{visible.map(c=>{const rate=c.recipients?Math.round(c.replies/c.recipients*100):0;return <tr className="hover:bg-slate-50" key={c.id}><td className="px-4 py-4 font-semibold"><Link className="text-blue-700 hover:underline" href={`/campaigns/${c.id}`}>{c.name}</Link></td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${badge[c.status]??badge.DRAFT}`}>{c.status}</span></td><td>{c.recipients}</td><td>{c.sent}</td><td>{c.followUps}</td><td>{c.replies}</td><td>{rate}%</td><td>{c.hardBounces}</td><td>{c.senders}</td><td>{c.status==="SCHEDULED"&&c.scheduledAt?new Date(c.scheduledAt).toLocaleString():c.status==="RUNNING"?"Due deliveries":"—"}</td><td>{new Date(c.updatedAt).toLocaleDateString()}</td></tr>})}</tbody></table></div>}</>}
