"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { validateRenderedCampaignMessage } from "@/modules/campaigns/domain/campaign-rules";
import { getAccountContext } from "@/modules/identity/server/get-account-context";
import { createPrivilegedSupabaseClient } from "@/modules/integrations/gmail/server/privileged-supabase";
import { normalizeCampaignEmail, parseCampaignCsv } from "@/modules/campaigns/domain/campaign-rules";
import { randomUUID } from "node:crypto";
import { ATTACHMENT_BUCKET,safeAttachmentFilename,sha256,validateAttachmentDescriptor,validateStepAttachmentSet } from "@/modules/campaigns/domain/attachment-rules";

const schema = z.object({ name:z.string().trim().min(1).max(200), subject:z.string().max(998), body:z.string().max(100000) });

export async function createCampaign(formData: FormData): Promise<void> {
  const account = await getAccountContext();
  if (!account?.workspaceId || !account.configurationComplete) redirect("/login");
  const parsed = schema.safeParse({ name:formData.get("name"),subject:formData.get("subject"),body:formData.get("body") });
  if (!parsed.success || validateRenderedCampaignMessage(parsed.data.subject, parsed.data.body)) redirect("/campaigns/new?error=invalid");
  const db = createPrivilegedSupabaseClient();
  const { data, error } = await db.from("email_campaigns").insert({ workspace_id:account.workspaceId,created_by:account.userId,name:parsed.data.name,subject_template:parsed.data.subject,body_text_template:parsed.data.body,status:"DRAFT",sequence_enabled:true }).select("id").single();
  if (error || !data) redirect("/campaigns/new?error=save");
  const {error:stepError}=await db.from("email_campaign_steps").insert({workspace_id:account.workspaceId,campaign_id:data.id,step_order:0,step_type:"INITIAL",delay_minutes:0,subject_template:parsed.data.subject,body_text_template:parsed.data.body,enabled:true});
  if(stepError) redirect("/campaigns/new?error=save");
  await db.from("email_campaign_events").insert({workspace_id:account.workspaceId,campaign_id:data.id,event_type:"CAMPAIGN_CREATED"});
  revalidatePath("/campaigns"); redirect(`/campaigns/new?campaignId=${data.id}&stage=audience`);
}

export async function updateCampaign(formData:FormData):Promise<void>{
  const context=await requireContext(); const id=z.string().uuid().parse(formData.get("campaignId")); const parsed=schema.safeParse({name:formData.get("name"),subject:formData.get("subject"),body:formData.get("body")});
  if(!parsed.success||validateRenderedCampaignMessage(parsed.data.subject,parsed.data.body)) return;
  const db=createPrivilegedSupabaseClient();await db.from("email_campaigns").update({name:parsed.data.name,subject_template:parsed.data.subject,body_text_template:parsed.data.body}).eq("id",id).eq("workspace_id",context.workspaceId).eq("status","DRAFT");await db.from("email_campaign_steps").update({subject_template:parsed.data.subject,body_text_template:parsed.data.body}).eq("campaign_id",id).eq("workspace_id",context.workspaceId).eq("step_order",0); revalidatePath(`/campaigns/${id}`);
}

export async function addCampaignFollowUp(formData:FormData):Promise<void>{const context=await requireContext();const campaignId=z.string().uuid().parse(formData.get("campaignId"));const delay=z.coerce.number().int().min(1).max(525600).parse(formData.get("delayMinutes"));const parsed=z.object({subject:z.string().trim().min(1).max(998),body:z.string().trim().min(1).max(100000)}).safeParse({subject:formData.get("subject"),body:formData.get("body")});if(!parsed.success)return;const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,campaignId,context.workspaceId))return;const {data:steps}=await db.from("email_campaign_steps").select("step_order").eq("campaign_id",campaignId).eq("workspace_id",context.workspaceId).order("step_order",{ascending:false}).limit(1);const order=(steps?.[0]?.step_order??0)+1;if(order>5)return;await db.from("email_campaign_steps").insert({workspace_id:context.workspaceId,campaign_id:campaignId,step_order:order,step_type:"FOLLOW_UP",delay_minutes:delay,subject_template:parsed.data.subject,body_text_template:parsed.data.body,enabled:true});revalidatePath(`/campaigns/${campaignId}`);}
export async function deleteLastCampaignFollowUp(formData:FormData):Promise<void>{const context=await requireContext();const parsed=z.object({campaignId:z.string().uuid(),stepId:z.string().uuid()}).safeParse({campaignId:formData.get("campaignId"),stepId:formData.get("stepId")});if(!parsed.success)return;const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,parsed.data.campaignId,context.workspaceId))return;const {data:last}=await db.from("email_campaign_steps").select("id,step_order").eq("workspace_id",context.workspaceId).eq("campaign_id",parsed.data.campaignId).order("step_order",{ascending:false}).limit(1).maybeSingle();if(!last||last.id!==parsed.data.stepId||last.step_order<1)return;await db.from("email_campaign_steps").delete().eq("id",last.id).eq("workspace_id",context.workspaceId).eq("campaign_id",parsed.data.campaignId).eq("step_order",last.step_order);revalidatePath(`/campaigns/${parsed.data.campaignId}`);}

export async function removeCampaignFollowUp(formData:FormData):Promise<void>{const context=await requireContext();const campaignId=z.string().uuid().parse(formData.get("campaignId"));const stepId=z.string().uuid().parse(formData.get("stepId"));const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,campaignId,context.workspaceId))return;const {data:step}=await db.from("email_campaign_steps").select("step_order").eq("id",stepId).eq("campaign_id",campaignId).eq("workspace_id",context.workspaceId).maybeSingle();const {data:max}=await db.from("email_campaign_steps").select("step_order").eq("campaign_id",campaignId).eq("workspace_id",context.workspaceId).order("step_order",{ascending:false}).limit(1).maybeSingle();if(!step||step.step_order===0||max?.step_order!==step.step_order)return;await db.from("email_campaign_steps").delete().eq("id",stepId).eq("workspace_id",context.workspaceId);revalidatePath(`/campaigns/${campaignId}`);}

export async function moveCampaignFollowUp(formData:FormData):Promise<void>{const context=await requireContext();const campaignId=z.string().uuid().parse(formData.get("campaignId"));const stepId=z.string().uuid().parse(formData.get("stepId"));const direction=z.enum(["UP","DOWN"]).parse(formData.get("direction"));const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,campaignId,context.workspaceId))return;const {data}=await db.from("email_campaign_steps").select("id,step_order").eq("campaign_id",campaignId).eq("workspace_id",context.workspaceId).order("step_order");if(!data)return;const index=data.findIndex(step=>step.id===stepId);const target=direction==="UP"?index-1:index+1;if(index<=0||target<=0||target>=data.length)return;const ordered=data.map(step=>step.id);[ordered[index],ordered[target]]=[ordered[target],ordered[index]];await db.rpc("reorder_email_campaign_steps",{p_workspace_id:context.workspaceId,p_campaign_id:campaignId,p_ordered_step_ids:ordered});revalidatePath(`/campaigns/${campaignId}`);revalidatePath(`/campaigns/new`);}

export async function setCampaignSenders(formData:FormData):Promise<void>{
  const context=await requireContext();const campaignId=z.string().uuid().parse(formData.get("campaignId"));const accountId=z.string().uuid().parse(formData.get("emailAccountId"));
  const daily=z.coerce.number().int().min(1).max(2000).parse(formData.get("dailyCap"));const minute=z.coerce.number().int().min(1).max(100).parse(formData.get("perMinuteCap"));const db=createPrivilegedSupabaseClient();
  if(!await isDraftCampaign(db,campaignId,context.workspaceId))return;
  const {data:account}=await db.from("email_accounts").select("id,scopes").eq("id",accountId).eq("workspace_id",context.workspaceId).eq("provider","GMAIL").eq("status","CONNECTED").maybeSingle();
  if(!account||(account.scopes as string[]).includes("https://www.googleapis.com/auth/gmail.send")===false)return;
  await db.from("email_campaign_senders").upsert({workspace_id:context.workspaceId,campaign_id:campaignId,email_account_id:accountId,daily_cap:daily,per_minute_cap:minute,enabled:true},{onConflict:"campaign_id,email_account_id"});revalidatePath(`/campaigns/${campaignId}`);
}

export async function transitionCampaign(formData:FormData):Promise<void>{
  const context=await requireContext();const id=z.string().uuid().parse(formData.get("campaignId"));const target=z.enum(["SCHEDULED","RUNNING","PAUSED","CANCELLED"]).parse(formData.get("target"));const db=createPrivilegedSupabaseClient();
  const {data:campaign}=await db.from("email_campaigns").select("id,status,subject_template,body_text_template").eq("id",id).eq("workspace_id",context.workspaceId).maybeSingle();if(!campaign)return;
  const allowed:Record<string,string[]>={DRAFT:["SCHEDULED","RUNNING"],SCHEDULED:["RUNNING","CANCELLED"],RUNNING:["PAUSED","CANCELLED"],PAUSED:["RUNNING","CANCELLED"]};if(!allowed[campaign.status]?.includes(target))return;
  if(target==="RUNNING"||target==="SCHEDULED"){
    if(validateRenderedCampaignMessage(campaign.subject_template,campaign.body_text_template))return;
    const [{count:recipients},{data:senders}]=await Promise.all([db.from("email_campaign_recipients").select("id",{count:"exact",head:true}).eq("campaign_id",id).eq("workspace_id",context.workspaceId),db.from("email_campaign_senders").select("id,email_accounts!inner(status,provider,scopes)").eq("campaign_id",id).eq("workspace_id",context.workspaceId).eq("enabled",true)]);if(!recipients||!senders?.some((sender)=>{const a=sender.email_accounts as unknown as {status:string;provider:string;scopes:string[]};return a.status==="CONNECTED"&&a.provider==="GMAIL"&&a.scopes.includes("https://www.googleapis.com/auth/gmail.send");}))return;
  }
  const now=new Date().toISOString();const scheduledRaw=String(formData.get("scheduledAt")??"");const patch:Record<string,unknown>={status:target};let event="";
  if(target==="SCHEDULED"){const date=new Date(scheduledRaw);if(!Number.isFinite(date.getTime())||date.getTime()<=Date.now())return;patch.scheduled_at=date.toISOString();event="CAMPAIGN_SCHEDULED";}
  if(target==="RUNNING"){patch.started_at=now;patch.paused_at=null;event=campaign.status==="PAUSED"?"CAMPAIGN_RESUMED":"CAMPAIGN_STARTED";}
  if(target==="PAUSED"){patch.paused_at=now;event="CAMPAIGN_PAUSED";}if(target==="CANCELLED"){patch.cancelled_at=now;event="CAMPAIGN_CANCELLED";}
  const {data:changed}=await db.from("email_campaigns").update(patch).eq("id",id).eq("workspace_id",context.workspaceId).eq("status",campaign.status).select("id").maybeSingle();if(changed){if(target==="RUNNING")await db.rpc("initialize_email_campaign_sequence",{p_workspace_id:context.workspaceId,p_campaign_id:id});if(target==="CANCELLED"){await db.from("email_campaign_recipients").update({status:"CANCELLED",engagement_status:"CANCELLED",stopped_reason:"CAMPAIGN_CANCELLED"}).eq("campaign_id",id).eq("workspace_id",context.workspaceId).eq("status","PENDING");await db.from("email_campaign_recipient_steps").update({status:"CANCELLED",safe_error_code:"CAMPAIGN_CANCELLED"}).eq("campaign_id",id).eq("workspace_id",context.workspaceId).eq("status","PENDING");}await db.from("email_campaign_events").insert({workspace_id:context.workspaceId,campaign_id:id,event_type:event});}revalidatePath(`/campaigns/${id}`);revalidatePath("/campaigns");
}

export async function importCampaignAudience(formData:FormData):Promise<void>{
  const context=await requireContext();const campaignId=z.string().uuid().parse(formData.get("campaignId"));const file=formData.get("file");if(!(file instanceof File)||file.size>5_000_000)return;
  const draftDb=createPrivilegedSupabaseClient();if(!await isDraftCampaign(draftDb,campaignId,context.workspaceId))return;
  let rows:unknown[][];if(file.name.toLowerCase().endsWith(".xlsx")){const {readSheet}=await import("read-excel-file/node");rows=await readSheet(Buffer.from(await file.arrayBuffer()),1);}else rows=parseCampaignCsv(await file.text());
  if(rows.length<2||rows.length>5001||rows[0].length>100)return;const headers=rows[0].map((v)=>String(v??"").trim().toLowerCase());const emailIndex=headers.indexOf("email");if(emailIndex<0)return;const db=createPrivilegedSupabaseClient(),sourceRows=rows.length-1;let validRows=0,duplicateRows=0,invalidEmailRows=0,suppressedRows=0,addedRows=0;const seen=new Set<string>();const [{data:existing},{data:suppressed}]=await Promise.all([db.from("email_campaign_recipients").select("normalized_email").eq("workspace_id",context.workspaceId).eq("campaign_id",campaignId),db.from("email_suppressions").select("normalized_email").eq("workspace_id",context.workspaceId)]);const campaignEmails=new Set((existing??[]).map(x=>x.normalized_email)),suppressedEmails=new Set((suppressed??[]).map(x=>x.normalized_email));
  for(const row of rows.slice(1)){const email=normalizeCampaignEmail(row[emailIndex]);if(!email){invalidEmailRows++;continue}validRows++;if(seen.has(email)||campaignEmails.has(email)){duplicateRows++;continue}seen.add(email);if(suppressedEmails.has(email)){suppressedRows++;continue}const value=(...keys:string[])=>{const index=keys.map(k=>headers.indexOf(k)).find(i=>i>=0);return index===undefined?null:String(row[index]??"").trim()||null;};const known=new Set(["email","name","first_name","last_name","company","position","job_title"]);const custom=Object.fromEntries(headers.map((h,i)=>[h,String(row[i]??"")]).filter(([h])=>h&&!known.has(h)));const {error}=await db.from("email_campaign_recipients").insert({workspace_id:context.workspaceId,campaign_id:campaignId,email,normalized_email:email,display_name:value("name"),company:value("company"),position:value("position","job_title"),personalization_json:{first_name:value("first_name")??"",last_name:value("last_name")??"",...custom}});if(!error){addedRows++;campaignEmails.add(email)}else duplicateRows++}
  const result={sourceRows,validRows,duplicateRows,invalidEmailRows,suppressedRows,addedRows};if(addedRows)await db.from("email_campaign_events").insert({workspace_id:context.workspaceId,campaign_id:campaignId,event_type:"AUDIENCE_IMPORTED",metadata:result});revalidatePath(`/campaigns/${campaignId}`);redirect(`/campaigns/new?campaignId=${campaignId}&stage=audience&${new URLSearchParams(Object.entries(result).map(([k,v])=>[k,String(v)])).toString()}`);
}

export async function addCampaignContacts(formData:FormData):Promise<void>{const context=await requireContext();const campaignId=z.string().uuid().parse(formData.get("campaignId"));const ids=formData.getAll("contactId").map(String).filter((id)=>z.string().uuid().safeParse(id).success).slice(0,5000);if(!ids.length)return;const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,campaignId,context.workspaceId))return;const {data:contacts}=await db.from("contacts").select("id,full_name,email,job_title,company_id,companies(name)").eq("workspace_id",context.workspaceId).in("id",ids);const normalized=(contacts??[]).map(c=>({contact:c,email:normalizeCampaignEmail(c.email)}));const valid=normalized.filter((x):x is typeof x&{email:string}=>Boolean(x.email));const [{data:existing},{data:suppressed}]=await Promise.all([db.from("email_campaign_recipients").select("normalized_email").eq("workspace_id",context.workspaceId).eq("campaign_id",campaignId),db.from("email_suppressions").select("normalized_email").eq("workspace_id",context.workspaceId)]);const existingSet=new Set((existing??[]).map(x=>x.normalized_email)),suppressedSet=new Set((suppressed??[]).map(x=>x.normalized_email)),seen=new Set<string>();let duplicateRows=0,suppressedRows=0,addedRows=0;for(const {contact,email} of valid){if(seen.has(email)||existingSet.has(email)){duplicateRows++;continue}seen.add(email);if(suppressedSet.has(email)){suppressedRows++;continue}const company=contact.companies as unknown as {name:string}|null;const {error}=await db.from("email_campaign_recipients").insert({workspace_id:context.workspaceId,campaign_id:campaignId,contact_id:contact.id,email,normalized_email:email,display_name:contact.full_name,company:company?.name??null,position:contact.job_title,personalization_json:{}});if(!error){addedRows++;existingSet.add(email)}else duplicateRows++}const result={sourceRows:ids.length,validRows:valid.length,duplicateRows,invalidEmailRows:ids.length-valid.length,suppressedRows,addedRows};if(addedRows)await db.from("email_campaign_events").insert({workspace_id:context.workspaceId,campaign_id:campaignId,event_type:"AUDIENCE_IMPORTED",metadata:{source:"CRM",...result}});revalidatePath(`/campaigns/${campaignId}`);redirect(`/campaigns/new?campaignId=${campaignId}&stage=audience&${new URLSearchParams(Object.entries(result).map(([k,v])=>[k,String(v)])).toString()}`);}

export async function setEmailSuppression(formData:FormData):Promise<void>{const context=await requireContext();const email=normalizeCampaignEmail(formData.get("email"));if(!email)return;const db=createPrivilegedSupabaseClient();const {data:existing}=await db.from("email_suppressions").select("reason").eq("workspace_id",context.workspaceId).eq("normalized_email",email).maybeSingle();if(!existing)await db.from("email_suppressions").insert({workspace_id:context.workspaceId,normalized_email:email,reason:"MANUAL",source:"SETTINGS"});else if(existing.reason==="MANUAL")await db.from("email_suppressions").update({source:"SETTINGS"}).eq("workspace_id",context.workspaceId).eq("normalized_email",email).eq("reason","MANUAL");revalidatePath("/settings");}
export async function removeEmailSuppression(formData:FormData):Promise<void>{const context=await requireContext();const email=normalizeCampaignEmail(formData.get("email"));if(!email)return;await createPrivilegedSupabaseClient().from("email_suppressions").delete().eq("workspace_id",context.workspaceId).eq("normalized_email",email).eq("reason","MANUAL");revalidatePath("/settings");}

export async function uploadCampaignStepAttachment(formData:FormData):Promise<void>{const context=await requireContext();const parsed=z.object({campaignId:z.string().uuid(),stepId:z.string().uuid()}).safeParse({campaignId:formData.get("campaignId"),stepId:formData.get("stepId")}),file=formData.get("attachment");if(!parsed.success||!(file instanceof File)||validateAttachmentDescriptor(file.name,file.type,file.size))return;const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,parsed.data.campaignId,context.workspaceId))return;const {data:step}=await db.from("email_campaign_steps").select("id").eq("id",parsed.data.stepId).eq("campaign_id",parsed.data.campaignId).eq("workspace_id",context.workspaceId).maybeSingle();if(!step)return;const {data:links}=await db.from("email_campaign_step_attachments").select("sort_order,email_attachments!inner(size_bytes,sha256)").eq("workspace_id",context.workspaceId).eq("step_id",parsed.data.stepId).order("sort_order");const bytes=Buffer.from(await file.arrayBuffer()),digest=sha256(bytes),items=(links??[]).map(x=>x.email_attachments as unknown as {size_bytes:number;sha256:string});if(items.some(x=>x.sha256===digest)||validateStepAttachmentSet([...items.map(x=>({sizeBytes:x.size_bytes})),{sizeBytes:bytes.length}]))return;const id=randomUUID(),safe=safeAttachmentFilename(file.name,id),storagePath=`${context.workspaceId}/${parsed.data.campaignId}/${id}/${safe}`;const {error:uploadError}=await db.storage.from(ATTACHMENT_BUCKET).upload(storagePath,bytes,{contentType:file.type,upsert:false});if(uploadError)return;const {error:metadataError}=await db.from("email_attachments").insert({id,workspace_id:context.workspaceId,storage_bucket:ATTACHMENT_BUCKET,storage_path:storagePath,original_filename:file.name.normalize("NFKC"),safe_filename:safe,mime_type:file.type,size_bytes:bytes.length,sha256:digest,uploaded_by:context.userId,lifecycle_status:"ACTIVE"});if(metadataError){await db.storage.from(ATTACHMENT_BUCKET).remove([storagePath]);return;}const {error:linkError}=await db.from("email_campaign_step_attachments").insert({workspace_id:context.workspaceId,campaign_id:parsed.data.campaignId,step_id:parsed.data.stepId,attachment_id:id,sort_order:links?.length??0});if(linkError){await db.from("email_attachments").delete().eq("id",id).eq("workspace_id",context.workspaceId);await db.storage.from(ATTACHMENT_BUCKET).remove([storagePath]);return;}await db.from("email_campaign_events").insert({workspace_id:context.workspaceId,campaign_id:parsed.data.campaignId,event_type:"ATTACHMENT_ADDED",metadata:{attachment_id:id,step_id:parsed.data.stepId,size_bytes:bytes.length,mime_type:file.type}});revalidatePath(`/campaigns/${parsed.data.campaignId}`);revalidatePath("/campaigns/new");}

export async function removeCampaignStepAttachment(formData:FormData):Promise<void>{const context=await requireContext();const parsed=z.object({campaignId:z.string().uuid(),stepId:z.string().uuid(),attachmentId:z.string().uuid()}).safeParse({campaignId:formData.get("campaignId"),stepId:formData.get("stepId"),attachmentId:formData.get("attachmentId")});if(!parsed.success)return;const db=createPrivilegedSupabaseClient();if(!await isDraftCampaign(db,parsed.data.campaignId,context.workspaceId))return;const {data:item}=await db.from("email_attachments").select("storage_bucket,storage_path").eq("id",parsed.data.attachmentId).eq("workspace_id",context.workspaceId).maybeSingle();if(!item)return;const {error}=await db.from("email_campaign_step_attachments").delete().eq("workspace_id",context.workspaceId).eq("campaign_id",parsed.data.campaignId).eq("step_id",parsed.data.stepId).eq("attachment_id",parsed.data.attachmentId);if(error)return;await db.storage.from(item.storage_bucket).remove([item.storage_path]);await db.from("email_attachments").delete().eq("id",parsed.data.attachmentId).eq("workspace_id",context.workspaceId);await db.from("email_campaign_events").insert({workspace_id:context.workspaceId,campaign_id:parsed.data.campaignId,event_type:"ATTACHMENT_REMOVED",metadata:{attachment_id:parsed.data.attachmentId,step_id:parsed.data.stepId}});revalidatePath(`/campaigns/${parsed.data.campaignId}`);revalidatePath("/campaigns/new");}

export async function reorderCampaignStepAttachment(formData:FormData):Promise<void>{const context=await requireContext();const parsed=z.object({campaignId:z.string().uuid(),stepId:z.string().uuid(),attachmentId:z.string().uuid(),direction:z.enum(["UP","DOWN"])}).safeParse({campaignId:formData.get("campaignId"),stepId:formData.get("stepId"),attachmentId:formData.get("attachmentId"),direction:formData.get("direction")});if(!parsed.success)return;const db=createPrivilegedSupabaseClient();const {data}=await db.from("email_campaign_step_attachments").select("attachment_id").eq("workspace_id",context.workspaceId).eq("campaign_id",parsed.data.campaignId).eq("step_id",parsed.data.stepId).order("sort_order");if(!data)return;const ids=data.map(x=>x.attachment_id),index=ids.indexOf(parsed.data.attachmentId),target=parsed.data.direction==="UP"?index-1:index+1;if(index<0||target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target],ids[index]];await db.rpc("reorder_email_campaign_step_attachments",{p_workspace_id:context.workspaceId,p_campaign_id:parsed.data.campaignId,p_step_id:parsed.data.stepId,p_attachment_ids:ids});revalidatePath(`/campaigns/${parsed.data.campaignId}`);revalidatePath("/campaigns/new");}

async function requireContext(){const context=await getAccountContext();if(!context?.workspaceId||!context.configurationComplete)redirect("/login");return {...context,workspaceId:context.workspaceId};}
async function isDraftCampaign(db:ReturnType<typeof createPrivilegedSupabaseClient>,campaignId:string,workspaceId:string){const {data,error}=await db.from("email_campaigns").select("id").eq("id",campaignId).eq("workspace_id",workspaceId).eq("status","DRAFT").maybeSingle();return !error&&Boolean(data);}
