import {sanitizeSpreadsheetCell} from "./sequence-rules";
export interface ReportRecipient{id:string;engagement:string;status:string;repliedAt:string|null;senderAccountId:string|null}
export interface ReportStep{id:string;stepOrder:number;stepType:string;delayMinutes:number;subject:string}
export interface ReportDelivery{id:string;recipientId:string;stepId:string;stepOrder:number;status:string;eligibleAt:string;sentAt:string|null;senderAccountId:string|null;providerThreadId:string|null}
export interface ReportSender{accountId:string;email:string;enabled:boolean;campaignDailyCap:number;campaignMinuteCap:number;globalDailyCap:number;globalMinuteCap:number;dailyReserved:number;minuteReserved:number}
export interface CampaignMetrics{audienceTotal:number;uniqueContacted:number;messagesSent:number;initialSent:number;followUpsSent:number;replied:number;replyRate:number;hardBounced:number;hardBounceRate:number;unsubscribed:number;suppressed:number;failed:number;deliveryUnknown:number;active:number;completed:number}
export type StepMetric=ReportStep&{eligible:number;sent:number;failed:number;skipped:number;deliveryUnknown:number;repliesAfterStep:number;replyRate:number};export type SenderMetric=ReportSender&{sent:number;failed:number;deliveryUnknown:number;replies:number;hardBounces:number};export interface CampaignReport{campaign:CampaignMetrics;steps:StepMetric[];senders:SenderMetric[]}
const rate=(n:number,d:number)=>d?n/d:0;
export function aggregateCampaignReport(input:{recipients:ReportRecipient[];steps:ReportStep[];deliveries:ReportDelivery[];senders:ReportSender[]}):CampaignReport{const sent=input.deliveries.filter(d=>d.status==="SENT"),contacted=new Set(sent.map(d=>d.recipientId)),eng=(s:string)=>input.recipients.filter(r=>r.engagement===s).length,replied=eng("REPLIED"),hardBounced=eng("HARD_BOUNCED");const campaign={audienceTotal:input.recipients.length,uniqueContacted:contacted.size,messagesSent:sent.length,initialSent:sent.filter(d=>d.stepOrder===0).length,followUpsSent:sent.filter(d=>d.stepOrder>0).length,replied,replyRate:rate(replied,contacted.size),hardBounced,hardBounceRate:rate(hardBounced,contacted.size),unsubscribed:eng("UNSUBSCRIBED"),suppressed:input.recipients.filter(r=>r.status==="SUPPRESSED").length,failed:input.deliveries.filter(d=>d.status==="FAILED").length,deliveryUnknown:input.deliveries.filter(d=>d.status==="DELIVERY_UNKNOWN").length,active:eng("ACTIVE"),completed:eng("COMPLETED")};const attribution=new Map<string,string>();for(const r of input.recipients){if(r.engagement!=="REPLIED"||!r.repliedAt)continue;const candidates=sent.filter(d=>d.recipientId===r.id&&d.sentAt&&new Date(d.sentAt).getTime()<new Date(r.repliedAt!).getTime()).sort((a,b)=>new Date(b.sentAt!).getTime()-new Date(a.sentAt!).getTime()||b.stepOrder-a.stepOrder);if(candidates[0])attribution.set(r.id,candidates[0].stepId)}const steps=input.steps.map(step=>{const rows=input.deliveries.filter(d=>d.stepId===step.id),sentCount=rows.filter(d=>d.status==="SENT").length,repliesAfterStep=[...attribution.values()].filter(id=>id===step.id).length;return {...step,eligible:rows.filter(d=>["SENDING","SENT","FAILED","DELIVERY_UNKNOWN","SUPPRESSED","CANCELLED","SKIPPED_REPLY","SKIPPED_BOUNCE","SKIPPED_UNSUBSCRIBED"].includes(d.status)).length,sent:sentCount,failed:rows.filter(d=>d.status==="FAILED").length,skipped:rows.filter(d=>["SUPPRESSED","CANCELLED","SKIPPED_REPLY","SKIPPED_BOUNCE","SKIPPED_UNSUBSCRIBED"].includes(d.status)).length,deliveryUnknown:rows.filter(d=>d.status==="DELIVERY_UNKNOWN").length,repliesAfterStep,replyRate:rate(repliesAfterStep,sentCount)}});const senders=input.senders.map(sender=>{const rows=input.deliveries.filter(d=>d.senderAccountId===sender.accountId),ids=new Set(rows.map(d=>d.recipientId));return {...sender,sent:rows.filter(d=>d.status==="SENT").length,failed:rows.filter(d=>d.status==="FAILED").length,deliveryUnknown:rows.filter(d=>d.status==="DELIVERY_UNKNOWN").length,replies:input.recipients.filter(r=>r.engagement==="REPLIED"&&ids.has(r.id)).length,hardBounces:input.recipients.filter(r=>r.engagement==="HARD_BOUNCED"&&ids.has(r.id)).length}});return {campaign,steps,senders}}
export function toSafeCsv(headers:string[],rows:unknown[][]):string{const quote=(value:unknown)=>`"${String(sanitizeSpreadsheetCell(value)).replace(/"/g,'""')}"`;return [headers.map(quote).join(","),...rows.map(row=>row.map(quote).join(","))].join("\r\n")}
