import Link from "next/link";
import {CheckCircle2,Users,Mail,Send,ListChecks} from "lucide-react";
import {PageHeader} from "@/components/shared/page-header";
import {Button} from "@/components/ui/button";
import {addCampaignContacts,addCampaignFollowUp,createCampaign,deleteLastCampaignFollowUp,importCampaignAudience,moveCampaignFollowUp,setCampaignSenders,transitionCampaign} from "@/modules/campaigns/server/campaign-actions";
import {getCampaign} from "@/modules/campaigns/server/campaign-data";
import {listContacts} from "@/modules/crm/contacts/server/list-contacts";
import {listEmailAccounts} from "@/modules/integrations/gmail/server/list-email-accounts";
const stages=[{key:"basics",label:"Basics",icon:Mail},{key:"audience",label:"Audience",icon:Users},{key:"sequence",label:"Sequence",icon:ListChecks},{key:"senders",label:"Senders",icon:Send},{key:"review",label:"Review & Launch",icon:CheckCircle2}] as const;type Stage=(typeof stages)[number]["key"];
type Draft={id:string;name:string;status:string;email_campaign_recipients:{id:string;email:string;display_name:string|null;company:string|null}[];email_campaign_steps:{id:string;step_order:number;delay_minutes:number;subject_template:string}[];email_campaign_senders:{id:string}[]};
export default async function NewCampaignPage({searchParams}:{searchParams:Promise<{campaignId?:string;stage?:string}>}){const q=await searchParams;const stage=(stages.some(s=>s.key===q.stage)?q.stage:"basics") as Stage;const row=(q.campaignId?await getCampaign(q.campaignId):null) as unknown as Draft|null;if(stage!=="basics"&&(!row||row.status!=="DRAFT"))return <><PageHeader title="Campaign draft unavailable"/><Link href="/campaigns/new" className="text-blue-600">Create a new draft</Link></>;const [contacts,accounts]=row?await Promise.all([listContacts(),listEmailAccounts()]):[{contacts:[]},{accounts:[]}];const url=(s:Stage)=>`/campaigns/new?campaignId=${row?.id??""}&stage=${s}`;return <><PageHeader title="Create campaign" description="Five persisted stages with a final human launch review."/><div className="mb-6 grid gap-2 md:grid-cols-5">{stages.map((s,i)=><Link href={row?url(s.key):s.key==="basics"?"/campaigns/new":"#"} key={s.key} className={`rounded-xl border p-3 ${s.key===stage?"border-blue-300 bg-blue-50":"bg-white"}`}><s.icon className="mb-2 size-4 text-blue-600"/><p className="text-xs text-slate-500">Step {i+1}</p><p className="text-sm font-semibold">{s.label}</p></Link>)}</div>
{stage==="basics"&&<form action={createCampaign} className="max-w-4xl space-y-5 rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">Basics</h2><Field name="name" label="Campaign name" max={200}/><Field name="subject" label="Initial subject" max={998}/><label className="block text-sm font-medium">Initial plain-text message<textarea name="body" required maxLength={100000} rows={12} className="mt-2 w-full rounded-lg border p-3"/></label><p className="text-xs text-slate-500">Variables: {"{{name}}, {{first_name}}, {{last_name}}, {{company}}, {{position}}, {{email}}"}</p><Button>Save draft & continue</Button></form>}
{row&&stage==="audience"&&<Panel title="Audience" next={url("sequence")}>{(q as Record<string,string|undefined>).sourceRows&&<div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{[["Source","sourceRows"],["Valid","validRows"],["Duplicates","duplicateRows"],["Invalid","invalidEmailRows"],["Suppressed","suppressedRows"],["Added","addedRows"]].map(([label,key])=><div className="rounded border p-3 text-sm" key={key}><span className="text-slate-500">{label}</span><b className="block text-lg">{(q as Record<string,string|undefined>)[key]}</b></div>)}</div>}<div className="grid gap-4 lg:grid-cols-2"><form action={importCampaignAudience} className="space-y-3 rounded border p-4"><input type="hidden" name="campaignId" value={row.id}/><input type="file" name="file" accept=".csv,.xlsx" required/><Button>Import CSV/XLSX</Button></form><form action={addCampaignContacts} className="rounded border p-4"><input type="hidden" name="campaignId" value={row.id}/><div className="max-h-48 overflow-auto">{contacts.contacts.filter(c=>c.email).slice(0,100).map(c=><label className="block text-sm" key={c.id}><input type="checkbox" name="contactId" value={c.id}/> {c.fullName} — {c.email}</label>)}</div><Button>Add CRM contacts</Button></form></div><p className="text-sm">Current audience: <b>{row.email_campaign_recipients.length}</b></p>{row.email_campaign_recipients.slice(0,5).map(r=><p className="text-sm text-slate-600" key={r.id}>{r.display_name||r.email} · {r.company||"—"}</p>)}</Panel>}
{row&&stage==="sequence"&&<Panel title="Sequence" next={url("senders")}><div className="space-y-2">{row.email_campaign_steps.sort((a,b)=>a.step_order-b.step_order).map((s,i)=><div className="rounded border p-3" key={s.id}><b>{s.step_order===0?"Initial":`Follow-up ${s.step_order}`}</b> · wait {s.delay_minutes} minutes<br/>{s.subject_template}{s.step_order>0&&<div className="mt-2 flex gap-2">{(["UP","DOWN"] as const).map(d=><form action={moveCampaignFollowUp} key={d}><input type="hidden" name="campaignId" value={row.id}/><input type="hidden" name="stepId" value={s.id}/><input type="hidden" name="direction" value={d}/><button className="rounded border px-2 py-1 text-xs" disabled={(d==="UP"&&i===1)||(d==="DOWN"&&i===row.email_campaign_steps.length-1)}>{d==="UP"?"Move up":"Move down"}</button></form>)}{i===row.email_campaign_steps.length-1&&<form action={deleteLastCampaignFollowUp}><input type="hidden" name="campaignId" value={row.id}/><input type="hidden" name="stepId" value={s.id}/><button className="rounded border border-rose-200 px-2 py-1 text-xs text-rose-700">Delete</button></form>}</div>}</div>)}</div>{row.email_campaign_steps.length<6&&<form action={addCampaignFollowUp} className="grid gap-3 rounded border border-dashed p-4"><input type="hidden" name="campaignId" value={row.id}/><input name="delayMinutes" type="number" min="1" defaultValue="1440"/><input name="subject" required placeholder="Follow-up subject"/><textarea name="body" required placeholder="Plain-text body"/><Button>Add follow-up</Button></form>}</Panel>}
{row&&stage==="senders"&&<Panel title="Senders" next={url("review")}><form action={setCampaignSenders} className="grid gap-3 md:grid-cols-4"><input type="hidden" name="campaignId" value={row.id}/><select name="emailAccountId">{accounts.accounts.filter(a=>a.status==="CONNECTED"&&a.sendEnabled).map(a=><option value={a.id} key={a.id}>{a.emailAddress}</option>)}</select><input name="dailyCap" type="number" min="1" defaultValue="100"/><input name="perMinuteCap" type="number" min="1" defaultValue="10"/><Button>Configure sender</Button></form><p className="text-sm">Configured: {row.email_campaign_senders.length}. Rotation respects campaign and global quota.</p></Panel>}
{row&&stage==="review"&&<Panel title="Review"><dl className="grid gap-3 md:grid-cols-2"><dt>Campaign</dt><dd>{row.name}</dd><dt>Audience</dt><dd>{row.email_campaign_recipients.length}</dd><dt>Sequence</dt><dd>{row.email_campaign_steps.length} steps</dd><dt>Senders</dt><dd>{row.email_campaign_senders.length}</dd></dl>{(!row.email_campaign_recipients.length||!row.email_campaign_senders.length)&&<p className="rounded bg-amber-50 p-3 text-sm">Launch blocked: audience and a send-enabled Gmail sender are required.</p>}<div className="flex flex-wrap gap-3"><Launch id={row.id} target="RUNNING" disabled={!row.email_campaign_recipients.length||!row.email_campaign_senders.length}/><form action={transitionCampaign} className="flex gap-2"><input type="hidden" name="campaignId" value={row.id}/><input type="hidden" name="target" value="SCHEDULED"/><input name="scheduledAt" type="datetime-local" required/><Button disabled={!row.email_campaign_recipients.length||!row.email_campaign_senders.length}>Schedule</Button></form></div></Panel>}</>}
function Field({name,label,max}:{name:string;label:string;max:number}){return <label className="block text-sm font-medium">{label}<input name={name} required maxLength={max} className="mt-2 h-11 w-full rounded-lg border px-3"/></label>}
function Panel({title,next,children}:{title:string;next?:string;children:React.ReactNode}){return <section className="max-w-5xl space-y-5 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">{title}</h2>{children}{next&&<Link href={next} className="inline-flex rounded bg-blue-600 px-4 py-2 text-sm text-white">Save & continue</Link>}</section>}
function Launch({id,target,disabled}:{id:string;target:"RUNNING";disabled:boolean}){return <form action={transitionCampaign}><input type="hidden" name="campaignId" value={id}/><input type="hidden" name="target" value={target}/><Button disabled={disabled}>Start</Button></form>}
