import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/shared/page-header";
import { getCampaignAudience,getCampaignDetail } from "@/modules/campaigns/server/campaign-data";
import { getCanonicalCampaignReport } from "@/modules/campaigns/server/campaign-reporting";
import { transitionCampaign } from "@/modules/campaigns/server/campaign-actions";

type Attachment={sort_order:number;email_attachments:{id:string;original_filename:string;mime_type:string;size_bytes:number}};
type Detail={id:string;name:string;status:string;sequence_enabled:boolean;scheduled_at:string|null;started_at:string|null;completed_at:string|null;email_campaign_steps:{id:string;step_order:number;step_type:string;delay_minutes:number;subject_template:string;body_text_template:string;email_campaign_step_attachments:Attachment[]}[];email_campaign_events:{id:string;event_type:string;created_at:string}[]};
const filters=["ALL","ACTIVE","PENDING","SENT","REPLIED","HARD_BOUNCED","UNSUBSCRIBED","SUPPRESSED","FAILED","DELIVERY_UNKNOWN","COMPLETED"];
const bytes=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;

export default async function CampaignDetailPage({params,searchParams}:{params:Promise<{campaignId:string}>;searchParams:Promise<{q?:string;audienceStatus?:string;page?:string;pageSize?:string}>}){
  const {campaignId}=await params,q=await searchParams;
  const [raw,report,audience]=await Promise.all([getCampaignDetail(campaignId),getCanonicalCampaignReport(campaignId),getCampaignAudience(campaignId,{q:q.q,status:q.audienceStatus,page:Number(q.page)||1,pageSize:Number(q.pageSize)||25})]);
  if(!raw||!report)notFound();const row=raw as unknown as Detail,m=report.campaign,percent=(n:number)=>`${(n*100).toFixed(1)}%`,href=(page:number)=>`?q=${encodeURIComponent(q.q??"")}&audienceStatus=${q.audienceStatus??"ALL"}&pageSize=${audience.pageSize}&page=${page}#audience`;
  return <div className="mx-auto max-w-[1600px] space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><PageHeader title={row.name} description={`${row.sequence_enabled?"Email sequence":"Legacy single send"} · Created campaign workspace`}/><div className="flex items-center gap-2"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">{row.status}</span>{row.status==="DRAFT"&&<Link className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white" href={`/campaigns/new?campaignId=${row.id}&stage=review`}>Continue setup</Link>}{row.status==="RUNNING"&&<CampaignAction id={row.id} target="PAUSED" label="Pause"/>}{row.status==="PAUSED"&&<CampaignAction id={row.id} target="RUNNING" label="Resume"/>}</div></div>
  <div className="grid gap-3 sm:grid-cols-3"><Meta label="Schedule" value={row.scheduled_at?new Date(row.scheduled_at).toLocaleString():"Immediate / not scheduled"}/><Meta label="Started" value={row.started_at?new Date(row.started_at).toLocaleString():"Not started"}/><Meta label="Completed" value={row.completed_at?new Date(row.completed_at).toLocaleString():"Not completed"}/></div>
  <nav className="sticky top-0 z-10 flex gap-6 overflow-x-auto border-b bg-slate-50/95 py-3 text-sm font-medium text-slate-600 backdrop-blur">{["Overview","Audience","Sequence","Senders","Activity","Reports"].map(x=><a className="whitespace-nowrap hover:text-blue-700 focus-visible:outline-2" href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</nav>
  <section id="overview"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries({Audience:m.audienceTotal,"Unique contacted":m.uniqueContacted,"Messages sent":m.messagesSent,Replies:m.replied,"Reply rate":percent(m.replyRate),"Hard bounced":m.hardBounced,Unsubscribed:m.unsubscribed,Failed:m.failed,"Delivery unknown":m.deliveryUnknown,Completed:m.completed}).map(([k,v])=><div className="rounded-xl border bg-white p-4 shadow-sm" key={k}><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{k}</p><p className="mt-2 text-2xl font-semibold text-slate-900">{v}</p></div>)}</div></section>
  <section id="audience" className="rounded-xl border bg-white p-5 shadow-sm"><SectionTitle title="Audience" detail={`${audience.total} recipients`}/><form className="mt-4 flex flex-wrap gap-2"><input aria-label="Search audience" name="q" defaultValue={q.q} placeholder="Search email, name, company" className="h-10 min-w-64 flex-1 rounded-lg border px-3"/><select aria-label="Audience status" name="audienceStatus" defaultValue={q.audienceStatus??"ALL"} className="h-10 rounded-lg border px-3">{filters.map(x=><option key={x}>{x}</option>)}</select><button className="h-10 rounded-lg border px-4">Apply</button></form><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr>{["Name / Email","Company","Engagement","Step","Messages","Last activity"].map(x=><th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{audience.rows.map(r=><tr className="border-t hover:bg-slate-50" key={r.id}><td className="max-w-72 px-3 py-3"><b className="block truncate">{r.display_name||"—"}</b><span className="block truncate">{r.email}</span></td><td>{r.company||"—"}</td><td>{r.engagement_status}</td><td>{r.last_sent_step_order??"—"}</td><td>{r.messagesSent}</td><td>{r.last_engagement_at?new Date(r.last_engagement_at).toLocaleString():"—"}</td></tr>)}</tbody></table>{!audience.rows.length&&<Empty text="No recipients match this view."/>}</div><div className="mt-4 flex justify-between text-sm"><span>Page {audience.page}/{audience.totalPages}</span><div className="flex gap-3">{audience.page>1&&<Link href={href(audience.page-1)}>Previous</Link>}{audience.page<audience.totalPages&&<Link href={href(audience.page+1)}>Next</Link>}</div></div></section>
  <section id="sequence" className="rounded-xl border bg-white p-5 shadow-sm"><SectionTitle title="Sequence" detail={`${row.email_campaign_steps.length} steps`}/><div className="mt-4 space-y-4">{row.email_campaign_steps.sort((a,b)=>a.step_order-b.step_order).map(step=>{const files=[...(step.email_campaign_step_attachments??[])].sort((a,b)=>a.sort_order-b.sort_order);return <article className="relative rounded-xl border p-5" key={step.id}><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-semibold uppercase text-blue-700">{step.step_order===0?"Initial":`Follow-up ${step.step_order}`}</p><h3 className="mt-1 font-semibold">{step.subject_template}</h3></div><span className="text-sm text-slate-500">Wait {step.delay_minutes} minutes</span></div><p className="mt-3 whitespace-pre-wrap break-words text-sm text-slate-600">{step.body_text_template}</p><div className="mt-4 rounded-lg bg-slate-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Attachments ({files.length})</p>{files.length===0?<p className="mt-2 text-sm text-slate-500">No attachments configured for this step.</p>:<div className="mt-2 grid gap-2">{files.map(link=>{const file=link.email_attachments;return <Link className="flex min-w-0 items-center justify-between gap-3 rounded-lg border bg-white px-3 py-2 text-sm hover:border-blue-300 focus-visible:outline-2" href={`/api/campaigns/${row.id}/attachments/${file.id}`} key={file.id}><span className="truncate font-medium">{file.original_filename}</span><span className="shrink-0 text-xs text-slate-500">{bytes(file.size_bytes)} · {file.mime_type}</span></Link>})}</div>}</div></article>})}</div></section>
  <section id="senders" className="rounded-xl border bg-white p-5 shadow-sm"><SectionTitle title="Senders" detail="Quota and delivery health"/><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50"><tr>{["Email","Campaign caps","Global caps","Usage","Sent","Failed","Unknown","Replies"].map(x=><th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{report.senders.map(s=><tr className="border-t text-center" key={s.accountId}><td className="px-3 py-3 text-left font-medium">{s.email}</td><td>{s.campaignDailyCap}/day · {s.campaignMinuteCap}/min</td><td>{s.globalDailyCap}/day · {s.globalMinuteCap}/min</td><td>{s.dailyReserved}/day · {s.minuteReserved}/min</td><td>{s.sent}</td><td>{s.failed}</td><td>{s.deliveryUnknown}</td><td>{s.replies}</td></tr>)}</tbody></table>{!report.senders.length&&<Empty text="No sender configured."/>}</div></section>
  <section id="activity" className="rounded-xl border bg-white p-5 shadow-sm"><SectionTitle title="Activity" detail="Latest 100 events"/>{row.email_campaign_events.length===0?<Empty text="No campaign activity yet."/>:<div className="mt-3 divide-y">{row.email_campaign_events.slice(0,100).map(e=><div className="flex flex-wrap justify-between gap-2 py-3 text-sm" key={e.id}><span>{e.event_type.toLowerCase().replaceAll("_"," ")}</span><time className="text-slate-500">{new Date(e.created_at).toLocaleString()}</time></div>)}</div>}</section>
  <section id="reports" className="rounded-xl border bg-white p-5 shadow-sm"><SectionTitle title="Reports" detail="Canonical campaign reporting"/><div className="mt-4 flex gap-2"><Link href={`/api/campaigns/${campaignId}/export?format=csv`} className="rounded-lg border px-4 py-2 text-sm">Export CSV</Link><Link href={`/api/campaigns/${campaignId}/export?format=xlsx`} className="rounded-lg border px-4 py-2 text-sm">Export XLSX</Link></div></section></div>;
}
function SectionTitle({title,detail}:{title:string;detail:string}){return <div className="flex items-baseline justify-between gap-3"><h2 className="text-lg font-semibold">{title}</h2><p className="text-sm text-slate-500">{detail}</p></div>}
function Meta({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-slate-500">{text}</p>}
function CampaignAction({id,target,label}:{id:string;target:"RUNNING"|"PAUSED";label:string}){return <form action={transitionCampaign}><input type="hidden" name="campaignId" value={id}/><input type="hidden" name="target" value={target}/><button className="rounded-lg border px-4 py-2 text-sm font-medium">{label}</button></form>}
